### ISSUE TITLE
Issue with HEIC format

### ISSUE THREAD

**Issue by sposth** [iscc/iscc-sdk#106]
Experienced an issue with .heic file format.

See file and error report attached. 
 
[IMG_3945.HEIC.zip](https://github.com/iscc/iscc-sdk/files/12748558/IMG_3945.HEIC.zip)
![2023-09-28 12 48 17](https://github.com/iscc/iscc-sdk/assets/14913025/388a70bb-3220-4232-91f7-470759a2c6cd)

**Comment by titusz** [comment]
Fixed in iscc-sdk v0.6.0 ... iscc-web will need to update to fix the web demo.
